CREATE TABLE XXFND_LOOKUP_TYPES_D(
    request_id NUMBER,
    LOOKUP_TYPE_D VARCHAR2(30),
    LOOKUP_TYPE_MEANING_D VARCHAR2(80)
);

CREATE TABLE XXFND_LOOKUP_VALUES_D(
    request_id NUMBER,
	APPLICATION_ID NUMBER,
	LOOKUP_TYPE VARCHAR2(30),
    LOOKUP_TYPE_DESCRIPTION VARCHAR2(240),
	LOOKUP_CODE VARCHAR2(30),
	LOOKUP_CODE_MEANING VARCHAR2(80),
    LOOKUP_CODE_DESCRIPTION VARCHAR2(240),
	CREATION_DATE DATE
);